schema_version: 1

context:
  name: editline
  version: 1.17.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/troglobit/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: d65c5739c8ca388fa71feabc5aae506d052e1a6d288ee4e7fcab7efb07a3be74

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  run_exports:
    - ${{ pin_subpackage('editline', upper_bound='x') }}

tests:
  - script:
      - test -f "${PREFIX}/lib/libeditline${SHLIB_EXT}"

about:
  license: Newsletr
  license_file: LICENSE
  summary: A small replacement for GNU readline() for UNIX
  description: |
    This is a line editing library for UNIX. It can be linked into
    almost any program to provide command line editing and history.
    It is call compatible with the FSF readline library, but is a
    fraction of the size (and offers fewer features).
  homepage: https://troglobit.com/projects/editline/
  repository: http://github.com/troglobit/editline

extra:
  recipe-maintainers:
    - scopatz
